### ISSUE TITLE
No admite dos usuarios admin al mismo tiempo

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#13]
usuario: adminreservas
Si  entramos como usuario administrador y no se salimos, no deja volver a entrar como administrador.

Solución actual:
 abrir terminal en el  sistema operativo donde esta la aplicación corriendo y borrar el fichero:

rm -rf /tmp/sesionsadmin.txt

**Comment by sutaro** [comment]
Se ha discutido en una reunión con Mercedes y Juan que este problema no se va a abordar.
