### ISSUE TITLE
Copiar solicitudes de laboratorios del año anterior

### ISSUE THREAD

**Issue by sutaro** [umalcc/gestorlcc#24]
Muchos usuarios tienen las mismas asignaturas de un año para otro. Crear un botón para que se asignen las reservas del año anterior, eligiendo mediante un combobox la asignatura deseada.

**Comment by umalcc** [comment]
Se ha creado un botón copiar solicitudes en la página http://localhost:3000/solicitudusuariolabs.
Para ello se ha definido e implementado el método 'copy' en el controlador solicitudusuariolabs.
Falta por implementar el envío de una respuesta desde el método 'copy' al Ajax, con el objeto de informar al usuario sobre el éxito o no de la operación copiar.

Ver index.html.erb, donde está definida la función Ajax asociada al botón copiar solicitudes..

**Comment by sutaro** [comment]
Falta testear la funcionalidad, en principio está lista.

**Comment by sutaro** [comment]
Es necesario mandar un email por cada solicitud copiada o bien meter todas las solicitudes y mandarlas en un email.

**Comment by umalcc** [comment]
se manda un email por cada solicitud copiada
