### ISSUE TITLE
Titulaciones ordenadas

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#50]

**Comment by sutaro** [comment]
Las titulaciones pasan a estar ordenadas en la vista index por la abreviatura. ¿Es lo que se intentaba decir con este fallo?
http://localhost:3000/titulacions

**Comment by merchetosina** [comment]
Resulta incomodo buscar una titulacion. Estoy dando de alta solicitudes y
me cuesta trabajo selecionar la titulacion. Deberian esta ordenada
alfabeticamente y tambien que se autocompletara cuando escribes.

**Comment by sutaro** [comment]
En esta vista las titulaciones están ordenadas. ¿Podrías darme un ejemplo? Hay que tener en cuenta que en un orden alfabético las mayúsculas van antes que las minúsculas. ¿Prefieres que en tal orden no se tengan las mayúsculas o minúsculas?

![image](https://cloud.githubusercontent.com/assets/3731966/6114999/985e47a6-b0a2-11e4-9bde-7b5af3111d8f.png)

**Comment by merchetosina** [comment]
Hay que entra como usuario normal , al dar de alta una solicitud de laboratorio

**Comment by sutaro** [comment]
Ya hemos corregido el fallo, hemos detectado que en varios sitios estaban ordenadas por id en lugar del nombre y han sido corregidos también.
Vamos a intentar buscar una solución para que busquéis de forma más cómoda en las listas
