### ISSUE TITLE
Mensaje de error al crear una nueva solicitud

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#52]
![pfc4](https://cloud.githubusercontent.com/assets/9946683/6059573/b34b0de6-ad33-11e4-9a95-a54eb46ead1f.PNG)

 He salido y vuelto a entrar y ya no ha salido el error

el usuario era: gabriel

**Comment by umalcc** [comment]
Pasos para reproducir el fallo:

1) Iniciar sesión como 'gabriel' usando una password errónea

2) Iniciar sesión otra vez con los datos correctos

3) Crear nueva solicitud de laboratorio en período lectivo: aparece el mensaje de error como el de la imagen superior adjunta.

**Comment by sutaro** [comment]
Solventado el problema sustituyendo flash[: por flash.now[: en todas las vistas.
