### ISSUE TITLE
Curso erroneo en algunas titulaciones

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#53]
Al crear una solicitud nueva, en algunas titulaciones, la asignatura aparece en curso "optativa" cuando en realidad es de otro curso. En la imagen esta asignatura es de curso "1"

![pfc5](https://cloud.githubusercontent.com/assets/9946683/6059632/4f1509fc-ad34-11e4-9bcb-8928adfec454.PNG)

**Comment by sutaro** [comment]
Después de analizar la base de datos he visto que no parece ser un fallo. Efectivamente existe una asignatura que es considerada optativa:
![image](https://cloud.githubusercontent.com/assets/3731966/6060824/b0cbd510-ad41-11e4-81ae-5f9d7a46839b.png)

**Comment by merchetosina** [comment]
Pero cuando creas una nueva solicitud solo aparece en optativa y no en 1º. Intenta reporoducir imagen primera que envié creando una nueva solicitud para curso 1 º .

**Comment by sutaro** [comment]
En una charla con Merche se llegó a la conclusión de que estaba todo bien.
