### ISSUE TITLE
Copiar solicitudes anteriores

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#54]
Sigo si entender como funciona

estoy introduciendo una nueva solicitud para el usuario "enesto", he pinchado "Copiar solicitud" y no hace nada se queda pensando:
![pfc6](https://cloud.githubusercontent.com/assets/9946683/6109573/03e44484-b07c-11e4-81b9-d038a3315ebb.PNG)

**Comment by umalcc** [comment]
Solucionado. 

El botón copiar solicitudes sólo está disponible cuando el usuario tiene solicitudes del curso académico pasado. Si es así, las copia pero actualizando las fechas al curso actual.
Cuando finaliza el proceso de copiado, aparece un mensaje que informa sobre el estado de la operación.

También añadir que, el usuario puede elegir las asignaturas que quiere copiar, las cuales se encuentran en la lista situada justo encima del botón de copia.
