### ISSUE TITLE
Error al dar de lata una asignatura

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#55]
![pfc7](https://cloud.githubusercontent.com/assets/9946683/6111299/176b9b04-b088-11e4-8f95-d22243303b6c.PNG)

La segunda vez que lo he intentado no ha dado problema y sí la ha dado de alta

**Comment by sutaro** [comment]
He dado de alta 10 asignaturas sin obtener el fallo. ¿Podrías indicarme algún patrón para reproducir el fallo?

**Comment by sutaro** [comment]
¿Quizás se ha insertado un espacio en blanco de forma errónea?

**Comment by merchetosina** [comment]
Puede ser eso que dices que tuviera algo mal el campo codigo, porque luego no dio problema.
