### ISSUE TITLE
Proceso de asignacion

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#58]
Ya hemos metido las solicitudes de este 2º cuatrimestre y en Asignacion perido lectivo / Proceso 
no hace nada, se supone que tendria que asignar laboratoriso y mostrar las colisiones

![pfc9](https://cloud.githubusercontent.com/assets/9946683/6125041/861ef05c-b112-11e4-88d3-0dae6f985376.PNG)

**Comment by umalcc** [comment]
Solucionado.
