### ISSUE TITLE
Contraseña de los usuarios

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#68]
Los usuarios leeran sus contraseñas del servidor LDAP.Cuando este implentada esta parte que aparazca el campo contraseña inaccesible.

Pero hemos pensado que nos interesa dejarlo por si alguna tarabajamos sin el servidor LDAP.

![pfc12](https://cloud.githubusercontent.com/assets/9946683/6165237/a4c5da4e-b2a6-11e4-8cd7-e2a91a0518a4.PNG)

**Comment by sutaro** [comment]
No acabo de entender bien este punto.
¿Se requiere que cuando no esté activado LDAP el campo contraseña permanezca inaccesible?

**Comment by merchetosina** [comment]
Al reves:
- La contraseña permanezca inaccesible si esta activado el LDAP.
- La contraseña permanezca accesible si no esta activado LDAP.

**Comment by sutaro** [comment]
¿Qué os parece la siguiente solución? Para nosotros es mucho más limpia.
Si el LDAP está inactivo, el campo contraseña permanece tal cual pero no se tiene en cuenta al hacer el login.

**Comment by merchetosina** [comment]
OK
