### ISSUE TITLE
Proceso de asignacion

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#70]
Asignaciones Periodo lectivo
Proceso
No funciona si pincho en "Asignacion unicial"
![pfc13](https://cloud.githubusercontent.com/assets/9946683/6331583/53124b14-bb80-11e4-84cf-2e6b6114a153.PNG)

**Comment by umalcc** [comment]
No entendemos bien cuál es la diferencia entre asignar_inicial y asignar_continuar.
¿Qué hace cada uno?

Gracias!

**Comment by merchetosina** [comment]
Asignar_iniciar : es partir de cero, de las solicitudes iniciales.
Asignar_continuar: partir desde los ajustes hechos anteriormente en el horario, ej: comienzas a trabajar  con el proceso de asignacion y lo dejas a la mitad porque no te da tiempo. Creo que es como funciona ahora mismo.

**Comment by umalcc** [comment]
Entiendo, y este proceso sólo puede llevarse a cabo cuando el período de admisión de solicitudes está cerrado,no?

**Comment by merchetosina** [comment]
Sí, mientras se está haciendo la asignación no esta abierto el perído de admisión de solicitudes.

**Comment by umalcc** [comment]
Hemos probado lo de asignación_iniciar y funciona. Eso sí, es un proceso lento porque tiene que realizar muchos cálculos para asignar los laboratorios.

**Comment by umalcc** [comment]
Hemos añadido un loader porque la operación es lenta y tarda en mostrar resultados.
