### ISSUE TITLE
Proceso asignacion : el horario no se ve bien

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#71]
Asignaciones periodo lectivo 
Proceso 
Asignacion en curso:

Horario: No se ve las asignaturas en horario ni las colisiones de forma clara

![pfc14](https://cloud.githubusercontent.com/assets/9946683/6331920/745265f0-bb82-11e4-918f-621492c957bb.PNG)

Ejemplo del programa actual de reservas, se ve mejor las colisiones y en general el horario :

![pfc15](https://cloud.githubusercontent.com/assets/9946683/6331929/86822f8a-bb82-11e4-83bf-d4ccc73f286b.PNG)

**Comment by umalcc** [comment]
Hola Merche,

sobre lo de que el horario no se ve bien, ¿podrías especificar cómo os gustaría o qué es lo que creéis que habría que mejorar?

En cuanto a las colisiones, estamos viendo si podemos añadir un marco rojo en aquellas casillas donde se produzcan.

**Comment by merchetosina** [comment]
Hola,

estuve trabajando ayer un rato en el horario y no veia claro lo que ponia y ademas me resultaba muy cansado a la vista (quizas el color de fondo de las reservas, el tamaño de la letra...) , en resumen no resulta comodo. Sinceramente no sabria como mejorarlo.

Ademas añado otro cosa que tampoco resulta comoda:
 cuando pasas el raton por encima de la reserva hay veces en que no aparece la leyenda de la reserva o tarda en aparecer.

**Comment by umalcc** [comment]
De momento, hemos cambiado el color de fondo de las asignaciones y nos quedaría solucionar el tema del ratón.

**Comment by merchetosina** [comment]
Ok  me gusta mas asi. No me ha dado tiempo a trabajar mucho con el pero la primera impesion al verlo ha sido buena

Al pinchar para moverlo, vuelve al color anterior.

**Comment by umalcc** [comment]
Sí, tenemos que cambiarlo también.

**Comment by umalcc** [comment]
Ya se ha solucionado lo del cambio de color al pinchar sobre la asignación.
