### ISSUE TITLE
Añadir un nuevo laboratorio 3.1.6

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#72]
Al crear un nuevo laboratorio,  lo pone al final en el horario (3.1.6):

![pfc16](https://cloud.githubusercontent.com/assets/9946683/6332446/ce9af20e-bb85-11e4-92e8-35ef8bd7a941.PNG)

**Comment by umalcc** [comment]
Solucionado. Ahora los laboratorios aparecen ordenados por su nombre.

**Comment by merchetosina** [comment]
OK
