### ISSUE TITLE
Lista de asignaciones

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#73]
Sigo en 
Asignaciones periodo lectivo
Proceso 

Cuando llevo una asignarura a "lista de asignaciones" y paso el raton por encima que aparezca tambien el horario y el dia de la solicitud
![pfc17](https://cloud.githubusercontent.com/assets/9946683/6332702/b471a4ca-bb87-11e4-85a6-24936a0ce6a9.PNG)

**Comment by umalcc** [comment]
Implementado.

**Comment by merchetosina** [comment]
Ok, si puedes poner tambien el numero de horas mejor.

**Comment by umalcc** [comment]
Sí, ya se añadido el número de horas totales de la solicitud, pero sólo en las asignaciones que no estaban en la lista externa, ¿quieres también en la lista externa?

**Comment by merchetosina** [comment]
Si podéis implementarlos sin mucho problema sí, mientras más información
tengamos cuando estamos asignando solicitudes en el horario mejor.

**Comment by umalcc** [comment]
Sí, no hay problema!

**Comment by umalcc** [comment]
Implementado.
