### ISSUE TITLE
Lista de asignaciones:  mover asignaturas al horario desde la lista

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#74]
![pfc18](https://cloud.githubusercontent.com/assets/9946683/6332923/63ee5d7a-bb89-11e4-914a-94082642f9d3.PNG)

He pasaso todas las reservas que hay el lunes por la mañana  de la asignatura "Prog. Or. Obj." a "Lista de asignaciones" para ir colocandolas de ahi al horario y no me funciona. No me deja hacer nada con ellas solo eliminarlas.

**Comment by sutaro** [comment]
No consigo reproducir el problema. ¿Puedes decirme cómo obtuviste el fallo?

Gracias!

**Comment by merchetosina** [comment]
En el horario del lunes por la mañana todas las solicitudes de la asignatura "Prog. Or. Obj"  entraban en conflicto en horario de 12.45 a 14.45.
Movi todas las solicitudes a Asignacuones temporales para despues ir colocandolas en el horario.

Por ejemplo, si quiero mover "Prog. Or. Obj" de las Asignaciones temporales al horario:
 Lunes , laboratorio 3.1.8, hora 12:45 a 13:45.
Pincho la asignatura con el raton y la desplazo pero no se queda en el horario.
Otro Fallo:
Si ya le he pinchado una vez , la segunda vez no deja arrastrarla.

**Comment by umalcc** [comment]
Solucionado.
