### ISSUE TITLE
Las horas no estan bien puesta en el horario

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#75]
Pone:
12:45 - 1:45
1:45 a 2:45

Deberia poner:
12:45 a 13:45
13:45 a 14:45

**Comment by umalcc** [comment]
Ya lo hemos corregido, pero estamos teniendo problemas para enviar los cambios  desde TeamViewer, no podemos conectarnos.

**Comment by umalcc** [comment]
Ya hemos conseguido conectarnos y los cambios han sido enviados.
