### ISSUE TITLE
Boton grabar asignacion definitiva

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#76]
Asignaciones Periodo Lectivo
Proceso
Asignacion en curso

Una vez que hemos realizado los ajustes en el horario para todos los días, ¿como paso a grabar las asignaciones definivas para obtener el horario?

**Comment by umalcc** [comment]
Acabamos de darnos cuenta de que falta ese botón.
Esta tarde intentaremos solucionar todos o casi todos los fallos que nos has comentado para que estén listos para mañana.

**Comment by umalcc** [comment]
Hemos añadido el botón y ya está disponible.
