### ISSUE TITLE
Numero de horas totales de una solicitud

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#77]
Nos interesaria que apareciera el numero de horas totales de la solicitud como información cuando se pasa el raton por encima (al menos cuando estamos ajustando las asignaciones).
Por ejemplo esta solicitud es de 3 horas:

![pfc20](https://cloud.githubusercontent.com/assets/9946683/6349091/0a887d9e-bc27-11e4-88c9-4992082103e7.PNG)

**Comment by umalcc** [comment]
Implementado.

**Comment by merchetosina** [comment]
Ademas tambien me gustaria que apareciera el horario inicial pedido por el profesor en la solicitud.
Esto es porque al mover la reserva a otra hora, cambia automaticamente la hora y si quiero volver al horario inicial ya no puedo saber cual era.

**Comment by umalcc** [comment]
Tal y como está implementado ahora, si se hace un cambio, se puede volver atrás cont Ctrl + Z,
pero sólo se permite deshacer un único cambio.

Hay una cosa que no nos queda del todo clara, sobre el calendario aparecen una serie de asignaciones y cada solicitud puede tener varias asignaciones. Por ejemplo:

Solicitud 1 -> Lunes 10:45 - 13:45

esto genera 3 asignaciones:

Asignación 1 -> Lunes 10:45 - 11:45
Asignación 2 -> Lunes 11:45 - 12:45
Asignación 3 -> Lunes 12:45 - 13:45

Cuando hablas del horario inicial de la solicitud, ¿quieres decir que cuando pases el ratón por encima de cada asignación aparezca Lunes 10:45 - 13:45?
