### ISSUE TITLE
Informacion sobre las solicitudes cuando pinchamos con raton sobre ellas

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#79]
La primera vez que lo hacemos funciona correctamente y muestra toda la informacion, las siguientes veces no funciona. 

Esto ocurre tanto en el horario como en las asignaciones temporales.

**Comment by merchetosina** [comment]
Quiero decir pasar con el ratón por encima de la solicitud.

**Comment by umalcc** [comment]
Sí, estamos al tanto de ello.
Ahora estamos centrados en otros problemas y cuando los solucionemos, pasaremos a corregir lo del ratón.

**Comment by umalcc** [comment]
Solucionado. Subiremos los cambios esta tarde.
