### ISSUE TITLE
Asignacion directa - error en tramos horarios

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#81]
Como usuario administrador
Asignaciones Periodo Lectivo
Consulta
Asignacion directa
Reserva normal

Si es la primera vez todo bien
Si ya he hecho antes una asignacuon directa en "tramos horarios" aparece la hora de la asignacion directa anterior

![pfc24](https://cloud.githubusercontent.com/assets/9946683/6446748/5073b22a-c10d-11e4-8d4f-0037a96aaf1c.PNG)

**Comment by umalcc** [comment]
Solucionado.
