### ISSUE TITLE
Solicitud de laboratorios para examen - No dejar seleccionar Titulacion

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#84]
Para hacer pruebas he abierto el periodo de exemane de Septiembre.

Usuario: profesor (en este caso guzman)
Solicitudes
Lab. examenes
Nueva solcitud
Al seleccionar Titulacion: aparece el desplegable con las titulaciones pero no dejar seleccionar ninguna:

![pfc30](https://cloud.githubusercontent.com/assets/9946683/6575716/a63356aa-c731-11e4-804e-41e08fcf68c5.PNG)

**Comment by umalcc** [comment]
Sí, en modo usuario ocurre ese fallo. 
Estamos en ello, así que subiremos los cambios esta noche.

**Comment by umalcc** [comment]
Solucionado.
