### ISSUE TITLE
Solicitudes Lab. examenes - No muestra Titulacion

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#86]
Como usuario administrador el en le listado de solicitudes que muestre la Titulación  cuando el ratón pasa sobre la asignatura.
![pfc31](https://cloud.githubusercontent.com/assets/9946683/6641515/7f67d8b0-c99e-11e4-93c1-c8b9f9425ccd.PNG)

**Comment by umalcc** [comment]
Solucionado.
