### ISSUE TITLE
Asignacion de examenes - No funciona mover

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#90]
En "Asignacion de examenes ", "Proceso":

![pfc37](https://cloud.githubusercontent.com/assets/9946683/7120251/0ef4e786-e20c-11e4-8caf-837176e4148f.PNG)

![pfc38](https://cloud.githubusercontent.com/assets/9946683/7120290/647dbafc-e20c-11e4-9d86-729802daa688.PNG)

Hay veces que si cambio del laboratoiro 3.1.1 al 3.1.9 (por ejemplo) mueve las cuatro horas a una sola hora:

![pfc39](https://cloud.githubusercontent.com/assets/9946683/7120390/3e1a5d92-e20d-11e4-99fa-01da539e994a.PNG)

Mover no hace nada.

**Comment by sutaro** [comment]
Listo para ser testeado, a la espera de feedback
