### ISSUE TITLE
Solicitud de examen tenga por defecto la fecha de inicio de examens

### ISSUE THREAD

**Issue by merchetosina** [umalcc/gestorlcc#92]
Cuando se esta generando una solicitud de examenes que tenga por defecto la fecha de inicio de examenes.
Version vuestra no la tiene (tiene la fecha de hoy)

![pfc43](https://cloud.githubusercontent.com/assets/9946683/8412957/7ce1f9e2-1e8d-11e5-957e-a715336fd4e6.PNG)

En la version anterior sí (01-09-2015) :

![pfc44](https://cloud.githubusercontent.com/assets/9946683/8412977/999cecd6-1e8d-11e5-8c23-db58137c3faa.PNG)

**Comment by sutaro** [comment]
Listo para ser testeado!
